name: gitlab-helper
version: 1.0.0
github: "L7R7/gitlab-helper"
license: Apache-2.0
author: "Leonhard Riedißer"
maintainer: "leo008180@googlemail.com"
copyright: "2024 Leonhard Riedißer"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/L7R7/gitlab-helper#readme>

dependencies:
  - base >= 4.7 && < 5
  - relude

default-extensions:
  - NoImplicitPrelude

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -fhide-source-paths
  - -Wpartial-fields
  - -Wmissing-deriving-strategies
  - -Wunused-packages

library:
  source-dirs: src
  ghc-options:
    - -fno-warn-orphans
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively
    - -Wmissing-export-lists
  dependencies:
    - aeson
    - autodocodec
    - barbies
    - burrito >= 2.0.1.0
    - colonnade
    - colourista
    - containers
    - directory
    - either
    - envparse
    - githash
    - http-conduit
    - http-types
    - gitlab-api-http-client-mtl
    - gitlab-api-types
    - network-uri
    - optparse-applicative
    - scientific
    - split
    - text
    - time
    - yaml

executables:
  gitlab-helper-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - gitlab-helper

tests:
  gitlab-helper-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - gitlab-helper
      - optparse-applicative
      - sydtest
