resolver: lts-24.44

packages:
  - .

extra-deps:
  - github: L7R7/gitlab-api
    commit: 93b751da90c6141f960e61ce3bc2f31da43e564a
    subdirs:
      - gitlab-api-http-client
      - gitlab-api-http-client-mtl
      - gitlab-api-types
  - github: NorfairKing/opt-env-conf
    commit: de7ac850e960c28e5182810515a87fbe1d6daede
    subdirs:
      - opt-env-conf
      - opt-env-conf-test
  - github: NorfairKing/safe-coloured-text
    commit: 5d1187b7873a8a1e397245c7c0c6d9ab88765d67
    subdirs:
      - safe-coloured-text
      - safe-coloured-text-layout
      - safe-coloured-text-gen
  - github: NorfairKing/autodocodec
    commit: 29b57dc2d425d732ce75143ecf3fc6411df0347b
    subdirs:
      - autodocodec
      - autodocodec-yaml
      - autodocodec-nix
      - autodocodec-schema

system-ghc: true

ghc-options:
  $everything: -split-sections
  "$locals": -fwrite-ide-info
