resolver: lts-22.38

packages:
  - .

extra-deps:
  - github: L7R7/gitlab-api
    commit: abff91cfa00788d28f57847aa7b28ad1d4f4a963
    subdirs:
      - gitlab-api-http-client
      - gitlab-api-http-client-mtl
      - gitlab-api-types

system-ghc: true

ghc-options:
  $everything: -split-sections
  "$locals": -fwrite-ide-info
