resolver: lts-22.22

packages:
  - .

extra-deps:
  - github: L7R7/gitlab-api
    commit: 0e3080a4fbc2d3f244d7b644537982da10f86489
    subdirs:
      - gitlab-api-http-client
      - gitlab-api-http-client-mtl
      - gitlab-api-types

system-ghc: true

ghc-options:
  $everything: -split-sections
  "$locals": -fwrite-ide-info
