resolver: lts-22.22

packages:
  - .

extra-deps:
  - github: L7R7/gitlab-api
    commit: db7ece328be2cbb7941270ef903c64ecc2ad23c7
    subdirs:
      - gitlab-api-http-client
      - gitlab-api-http-client-mtl
      - gitlab-api-types

system-ghc: true

ghc-options:
  $everything: -split-sections
  "$locals": -fwrite-ide-info
