resolver: lts-22.22

packages:
  - .

extra-deps:
  - github: L7R7/gitlab-api
    commit: db7ece328be2cbb7941270ef903c64ecc2ad23c7
    subdirs:
      - gitlab-api-http-client
      - gitlab-api-http-client-mtl
      - gitlab-api-types
  - github: NorfairKing/opt-env-conf
    commit: 2e6aaaa65eb3f5008b05c28adc29312bd8a47d46
    subdirs:
      - opt-env-conf
      - opt-env-conf-test
  - github: NorfairKing/safe-coloured-text
    commit: 61f14d21b7399fe97da24e484c2f9fedaf532bb8
    subdirs:
      - safe-coloured-text
      - safe-coloured-text-layout
      - safe-coloured-text-gen
  - github: NorfairKing/autodocodec
    commit: 36779707f38ec3aeb0a591ff8043a63717c96ea2
    subdirs:
      - autodocodec
      - autodocodec-yaml
      - autodocodec-schema

system-ghc: true

ghc-options:
  $everything: -split-sections
  "$locals": -fwrite-ide-info
