resolver: lts-22.22

packages:
  - .

extra-deps:
  - github: L7R7/gitlab-api
    commit: cdc01c1ff03f550c250acd2cb2f2a127de8158c1
    subdirs:
      - gitlab-api-http-client
      - gitlab-api-types

system-ghc: false
