resolver: lts-23.24

packages:
  - .

extra-deps:
  - github: L7R7/gitlab-api
    commit: 44c8a21ebe7607cfcf1bd74c2610e47f5df783fd
    subdirs:
      - gitlab-api-http-client
      - gitlab-api-http-client-mtl
      - gitlab-api-types

system-ghc: true

ghc-options:
  $everything: -split-sections
  "$locals": -fwrite-ide-info
