resolver: lts-24.43

packages:
  - .

extra-deps:
  - github: L7R7/gitlab-api
    commit: 93b751da90c6141f960e61ce3bc2f31da43e564a
    subdirs:
      - gitlab-api-http-client
      - gitlab-api-http-client-mtl
      - gitlab-api-types

system-ghc: true

ghc-options:
  $everything: -split-sections
  "$locals": -fwrite-ide-info
